In [3]:
import numpy as np

In [6]:
a,b = 0, 256
batch = np.random.randint(a, b, size=(32, 3, 1080, 1920)) # entre a et b-1
batch.shape

(32, 3, 1080, 1920)

In [8]:
batch[5, 0].shape

(1080, 1920)

In [ ]:
batch[5,:,0,0] 

array([80, 60, 98])

In [16]:
X = np.array([[1, 2], [3, 4], [5, 6]])
X

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
b = np.array([10, 100])
b

array([ 10, 100])

In [19]:
X + b

array([[ 11, 102],
       [ 13, 104],
       [ 15, 106]])